import React from 'react';

export default function Fechas() {
  return (
    <div className="page active" style={{ display: 'flex' }}>

  <div className="page-hdr"><div><div className="page-title">📅 Fechas de Pago</div><div className="page-sub">Calendario y recordatorios de vencimientos</div></div><button className="btn btn-o">+ Agregar Recordatorio</button></div>
  <div className="g4"><div className="sc sc-o"><div className="sc-label">Pagos Pendientes</div><div className="sc-val" style={{"color":"var(--orange)"}}>8</div><div className="sc-change ch-n">$2.150.000</div><div className="sc-icon">⏳</div></div><div className="sc sc-g"><div className="sc-label">Completados</div><div className="sc-val" style={{"color":"var(--green)"}}>2</div><div className="sc-change ch-n">$535.000</div><div className="sc-icon">✅</div></div><div className="sc sc-b"><div className="sc-label">Total Este Mes</div><div className="sc-val" style={{"color":"var(--blue)"}}>$3.400.000</div><div className="sc-icon">📅</div></div><div className="sc sc-p"><div className="sc-label">Próximo Pago</div><div className="sc-val" style={{"color":"var(--pink)","fontSize":"14px"}}>🔴 Vencido</div><div className="sc-change ch-dn">Internet VTR</div><div className="sc-icon">⚠️</div></div></div>
  <div className="alert al-p"><span className="al-icon">🔴</span><div className="al-body"><div className="al-title" style={{"color":"var(--pink)"}}>Pago Vencido</div>Internet VTR ($45.000) venció el 12 de Marzo. Págalo ahora para evitar corte de servicio.</div></div>
  <div className="card"><div className="card-hdr"><div className="card-title">📋 Pagos del Mes — Marzo 2025</div></div>
    <div className="tl-group"><div className="tl-date">✅ MARTES 10 DE MARZO — Completados</div><div className="tl-item"><div className="tl-dot" style={{"background":"rgba(126,211,33,0.15)"}}>✅</div><div style={{"flex":"1"}}><div className="tl-title">Agua y Luz</div><div className="tl-meta"><span className="badge bg">Completado</span></div></div><span className="tl-amt neg">$85.000</span></div><div className="tl-item"><div className="tl-dot" style={{"background":"rgba(126,211,33,0.15)"}}>✅</div><div style={{"flex":"1"}}><div className="tl-title">Cuota Hipotecaria</div><div className="tl-meta"><span className="badge bg">Completado</span></div></div><span className="tl-amt neg">$450.000</span></div></div>
    <div className="tl-group"><div className="tl-date" style={{"color":"var(--pink)"}}>🔴 VIERNES 12 DE MARZO — VENCIDO</div><div className="tl-item"><div className="tl-dot" style={{"background":"rgba(232,93,117,0.15)"}}>⏰</div><div style={{"flex":"1"}}><div className="tl-title">Internet VTR</div><div className="tl-meta"><span className="badge bp">Vencido</span></div></div><span className="tl-amt neg">$45.000</span><button className="btn btn-o btn-sm" style={{"marginLeft":"8px"}}>Pagar</button></div></div>
    <div className="tl-group"><div className="tl-date">⏳ DOMINGO 15 DE MARZO — Pendiente</div><div className="tl-item"><div className="tl-dot" style={{"background":"rgba(255,154,118,0.15)"}}>⏳</div><div style={{"flex":"1"}}><div className="tl-title">Arriendo</div><div className="tl-meta"><span className="badge bo">Pendiente</span></div></div><span className="tl-amt neg">$800.000</span><button className="btn btn-o btn-sm" style={{"marginLeft":"8px"}}>Pagar</button></div><div className="tl-item"><div className="tl-dot" style={{"background":"rgba(255,154,118,0.15)"}}>⏳</div><div style={{"flex":"1"}}><div className="tl-title">Cuota Préstamo BCI</div><div className="tl-meta"><span className="badge bo">Pendiente</span></div></div><span className="tl-amt neg">$250.000</span><button className="btn btn-o btn-sm" style={{"marginLeft":"8px"}}>Pagar</button></div></div>
    <div className="tl-group"><div className="tl-date">⏳ MIÉRCOLES 20 DE MARZO — Pendiente</div><div className="tl-item"><div className="tl-dot" style={{"background":"rgba(255,154,118,0.15)"}}>⏳</div><div style={{"flex":"1"}}><div className="tl-title">Pago Tarjeta de Crédito</div><div className="tl-meta"><span className="badge bo">Pendiente</span></div></div><span className="tl-amt neg">$450.000</span><button className="btn btn-o btn-sm" style={{"marginLeft":"8px"}}>Pagar</button></div><div className="tl-item"><div className="tl-dot" style={{"background":"rgba(255,154,118,0.15)"}}>⏳</div><div style={{"flex":"1"}}><div className="tl-title">Netflix</div><div className="tl-meta"><span className="badge bo">Pendiente</span></div></div><span className="tl-amt neg">$18.000</span><button className="btn btn-o btn-sm" style={{"marginLeft":"8px"}}>Pagar</button></div></div>
  </div>

    </div>
  );
}
